### ISSUE TITLE
Why you didn't mention original author?

### ISSUE THREAD

**Issue by funny-falcon** [loli-foundation/loli#10]
Original source code were written by other author: https://github.com/FascinatedBox/lily
You've changed language name, but didn't mention original author.
It sucks.

**Comment by funny-falcon** [comment]
https://gitlab.com/FascinatedBox/lily

**Comment by Injazz** [comment]
The most the MIT license required you to do is to CREDIT THE AUTHOR, yet you haven't for some reason?

**Comment by MWGuy** [comment]
WTF!?? This 100% original programming language

**Comment by funny-falcon** [comment]
Sorry, but this language is not 100% original: as of commit https://github.com/loli-foundation/loli/tree/abb7d15a51b933a8724d84fc819741a5d34c9346 your repository have same set of files, same internal structure in many files, almost same language syntax.

`if condition: { then_statement; else: else_statement }` is so strange syntax decision, that two human could not create it independently of each other. That is why I rememberred original language.
 Single noticable difference us `define` vs `fn`.

If you didn't wrote first lines of this "shine 100% new" language, then don't be so confident.

First commits author is @txlyre, so let him talk.

**Comment by prinstonsam** [comment]
It's like BolgenOS

**Comment by wafflecomposite** [comment]
so thats how good old **print** become freakin **_sayln_**...
Wow. Just wow. All you had to do is to keep original copyright mention.
But it's not the way for BolgenOS job, of course.

**Comment by MWGuy** [comment]
After analyzing the situation, and punishing the main developer, I will indicate the authorship, and that this is fork. And also I apologize for my being wrong, for I see this language for the first time. I hope for your understanding

**Comment by FlightBlaze** [comment]
Maybe delete this repository?

**Comment by Suvitruf** [comment]
> 
> 
> After analyzing the situation, and punishing the main developer, I will indicate the authorship, and that this is fork. And also I apologize for my being wrong, for I see this language for the first time. I hope for your understanding

Your 1st commit https://github.com/loli-foundation/loli/commit/e375a10b1a18010fd6b745a4a773a875fa6501ca was in January...

**Comment by funny-falcon** [comment]
In my opinion, if guys made some valuable addition (beside renaming), then it will be better to contribute them to original language, and talk with its author about some kind of partnership.

If this repository authors were so excited by language so they decided to excite others, then original language is certainly worth to try.

I think, consolidation of their energy with original author could bring us really useful new programming environment.

**Comment by mayorovp** [comment]
Then you need to add original copyright notice to license file...

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by Injazz** [comment]
Don't be so harsh on them, that's okay for them to borrow code on the conditions of MIT, and they're crediting author now. It's not like they are obligated to join the author (author can borrow their work himself), they can do whatever they want if they plan to proceed playing fair.

**Comment by MWGuy** [comment]
But @txlure did not tell me that he stole the source code, and was silent. Now we intend to forcefully change the language because of the harmonious circumstances. Once again, I hope for your understanding. And once again I apologize.

**Comment by Injazz** [comment]
Don't forget to update license file and include the copyright of original author

**Comment by MWGuy** [comment]
Ok

**Comment by MWGuy** [comment]
I think our problem is solved?

**Comment by funny-falcon** [comment]
@Injazz
> Don't be so harsh on them, that's okay for them to borrow code on the conditions of MIT, and they're crediting author now. It's not like they are obligated to join the author (author can borrow their work himself), they can do whatever they want if they plan to proceed playing fair.

Certainly you are right: they don't have to contribute changes back.
I've just said, it would be great if they collaborate with original author. Energy concentration is usually more efficient than spreading.

**Comment by funny-falcon** [comment]
> I think our problem is solved?

I think so. Thank you for taking correct decision!

**Comment by Injazz** [comment]
Well i don't know what MIT can tell on separate commit histories, but i guess it doesn't matter.
What I can say for certain is that the nature of fork doesn't matter for MIT, you can keep it detached.

**Comment by MWGuy** [comment]
> I think so. Thank you for taking correct decision!

Thank you for saying this right now, otherwise we would have more problems.

**Comment by MWGuy** [comment]
But it's a shame that my karma falls on habr.com, although I have no relation to this situation :C

**Comment by wafflecomposite** [comment]
Talking about the license, I think it's clean now.
But the number of unverified statements and deleted comments before resolution of this situation is far from being transparent.
And by the way, what the hell is this [https://github.com/loli-foundation/loli/blob/master/lolipop.py](https://github.com/loli-foundation/loli/blob/master/lolipop.py) file? Since it's pointing to txlure's website and doing god know what, would not it be better to remove it?

**Comment by MWGuy** [comment]
@wafflecomposite is are old package manager=)

**Comment by MWGuy** [comment]
@wafflecomposite and I deleted comments offensive character that are not relevant to this topic.
